---

- include_tasks: keepalived.yml
  tags: keepalived

- include_tasks: k3s_install.yml
  when: inventory_hostname == groups['master'][0]

- include_tasks: k3s_join.yml
  when: inventory_hostname != groups['master'][0]
