global:
  domain: homelab.beavertech.xyz
server:
  service:
    type: ClusterIP  # ClusterIP is the default, no need for LoadBalancer
  ingress:
    enabled: false
installCRDs: true
configs:
  params:
    server.insecure: true
