apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-base-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/benjdaun/homelab_base"
    targetRevision: "main"
    path: "base-applications"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: "default"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    