apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.10.4 # Use the latest version or the specific version you need
    chart: external-secrets

  destination:
    server: https://kubernetes.default.svc
    namespace: secrets-management

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

  # Customize the Helm values
  # Add any additional Helm values or configuration you need here
  helm:
    parameters:
      - name: installCRDs
        value: "true" # Installs CRDs if not already installed
      - name: replicaCount
        value: "1"
