apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 65.1.1
    chart: kube-prometheus-stack
    helm:
      valueFiles:
      - $values/configuration/prometheus-values.yaml
  - repoURL: https://github.com/benjdaun/homelab_base
    targetRevision: main
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: observability-stack

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true