---
- name: Get the k3s token from the server
  shell: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  delegate_to: "{{ groups['k3s_server'][0] }}"
  become: true

- name: Install k3s as an agent
  shell: |
    curl -sfL https://get.k3s.io | K3S_URL=https://{{ groups['k3s_server'][0] }}:6443 K3S_TOKEN={{ k3s_token.stdout }} INSTALL_K3S_EXEC="agent --node-name {{ node_name }}" sh -
  args:
    creates: /usr/local/bin/k3s

- name: Ensure k3s-agent service is enabled and started
  systemd:
    name: k3s-agent
    enabled: true
    state: started
