apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: homelab-prod-issuer
spec:
  acme:
    email: benjamindaunoravicius@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsentrypt-issuer-prod-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-token
            key: api-token