---
- hosts: k3s_server
  become: true
  tasks:
    - name: Install k3s on the server
      include_role:
        name: k3s_server

- hosts: k3s_agent
  become: true
  tasks:
    - name: Install k3s on the agent
      include_role:
        name: k3s_agent


- hosts: localhost
  become: true
  become_user: benjdaun
  tasks:
    - name: Apply Kubernetes Gateway API CRDs
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gatewayclasses.yaml && \
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_gateways.yaml && \
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_httproutes.yaml && \
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_referencegrants.yaml && \
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/standard/gateway.networking.k8s.io_grpcroutes.yaml && \
        kubectl apply -f https://raw.githubusercontent.com/kubernetes-sigs/gateway-api/v1.1.0/config/crd/experimental/gateway.networking.k8s.io_tlsroutes.yaml

- hosts: localhost
  become: true
  become_user: benjdaun
  tasks:
    - block:
        - name: Try to install Cilium
          shell: |
            cilium install -f /home/benjdaun/homelab_base/ansible/cilium-values.yaml
          register: cilium_install_result
          ignore_errors: true

      rescue:
        - name: Cilium install failed, trying upgrade instead
          shell: |
            cilium upgrade -f /home/benjdaun/homelab_base/ansible/cilium-values.yaml
          when: cilium_install_result.rc != 0  # Run upgrade only if install failed



- hosts: all
  become: yes
  tasks:
    - name: Install open-iscsi package
      ansible.builtin.package:
        name: open-iscsi
        state: present

    - name: Enable and start iscsid service
      ansible.builtin.systemd:
        name: iscsid
        enabled: yes
        state: started

    - name: Ensure iscsid daemon is running
      ansible.builtin.systemd:
        name: iscsid
        state: started