---
- name: Display execution information
  hosts: localhost
  gather_facts: false
  run_once: true
  tasks:
    - name: Display the unique hash
      debug:
        msg: "Unique hash for this execution: {{ unique_hash }}"

- name: Set up K3s servers with keepalived
  hosts: master
  become: yes
  serial: 1
  roles:
    - k3s-server

- name: Set up K3s agents
  hosts: agent
  become: yes
  roles:
    - k3s-agent

- name: Verify cluster status
  hosts: localhost
  gather_facts: false
  run_once: true
  tasks:
    - name: Display kubeconfig location
      debug:
        msg: "Kubeconfig available at: {{ project_dir }}/kubeconfigs/{{ env | default('dev') }}/{{ unique_hash }}-kubeconfig"
    
    - name: Test cluster connectivity
      shell: |
        export KUBECONFIG="{{ project_dir }}/kubeconfigs/{{ env | default('dev') }}/{{ unique_hash }}-kubeconfig"
        kubectl get nodes -o wide
      register: cluster_nodes
      ignore_errors: yes
    
    - name: Display cluster nodes
      debug:
        msg: "{{ cluster_nodes.stdout_lines }}"
      when: cluster_nodes.rc == 0
    
    - name: Display error if cluster not accessible
      debug:
        msg: "Unable to connect to cluster: {{ cluster_nodes.stderr }}"
      when: cluster_nodes.rc != 0
