apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-external-dns
  namespace: external-dns
spec:
  target:
    name: cloudflare-external-dns
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        cloudflare_api_token: |-
          {{ index . "api-token" }}
  data:
    - secretKey: api-token
      sourceRef:
        storeRef:
          name: bitwarden-login
          kind: ClusterSecretStore
      remoteRef:
        key: 664a596e-356f-4ffd-9c71-b1fb00e3fdb0
        property: password