require 'yaml'

# Load VM configuration from vm-set.yaml
config_file = File.join(File.dirname(__FILE__), "vagrant-vm-set.yml")
vm_config = YAML.load_file(config_file)

Vagrant.configure("2") do |config|
  # Base box to use
  config.vm.box = "ubuntu/focal64"
  config.ssh.insert_key = false

  # Create master VMs
  vm_config['servers']['quantity'].times do |i|
    config.vm.define "master-#{i + 1}" do |master|
      master.vm.hostname = "master-#{i + 1}"

      # Configure master resources
      master.vm.provider "virtualbox" do |vb|
        vb.cpus = vm_config['servers']['cpu']
        vb.memory = vm_config['servers']['ram'].to_i
        #vb.disk = vm_config['servers']['disk']
      end

      # Configure networking
      master.vm.network "private_network", type: "dhcp"

      # SSH setup
      master.vm.provision "file", source: File.expand_path("~/.ssh/id_rsa_homelab.pub"), destination: "/home/vagrant/.ssh/authorized_keys"
    end
  end

# Check if 'agents' is defined and has a quantity
if vm_config['agents'] && vm_config['agents']['quantity']
    vm_config['agents']['quantity'].times do |i|
      config.vm.define "agent-#{i + 1}" do |agent|
        agent.vm.hostname = "agent-#{i + 1}"
  
        # Configure agent resources
        agent.vm.provider "virtualbox" do |vb|
          vb.cpus = vm_config['agents']['cpu']
          vb.memory = vm_config['agents']['ram'].to_i
        end
  
        # Configure networking
        agent.vm.network "private_network", type: "dhcp", ip: "192.168.50.#{4+i}"
  
        # SSH setup
        agent.vm.provision "file",
                           source: File.expand_path("~/.ssh/id_rsa_homelab.pub"),
                           destination: "/home/vagrant/.ssh/authorized_keys"
      end
    end
end
end